name: fl_linux_window_manager
description: "Manage platform window of flutter application on linux"
version: 1.0.0
homepage: https://moduluz.io
repository: https://github.com/moduluz-io/fl-linux-window-manager.git
issue_tracker: https://github.com/moduluz-io/fl-linux-window-manager/issues
topics:
  - linux
  - window
  - wayland
  - layer

environment:
  sdk: ^3.6.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlLinuxWindowManagerPlugin
